language: node_js
node_js:
  - "node" # Latest node version
  - "lts/*" # Latest LTS version
  - "10"
  - "8"
  - "6"
  - "5"
  - "4.3.2"

before_install: if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi

script:
   - grunt standards
   - npm test

# For code coverage:
after_success:
   cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
